jobs:
  conda:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v5
    - uses: mamba-org/setup-micromamba@v2
      with:
        cache-downloads: true
        cache-environment: true
        create-args: python=${{ matrix.python-version }}
        environment-file: environment.yaml
        init-shell: bash powershell
        micromamba-version: 1.5.6-0
        post-cleanup: all
    - run: |-
        echo "Testing package import"
        python -c 'import fractopo'
        echo "Testing module entrypoint"
        python -m fractopo --help
        echo "Running unittests with pytest"
        pytest -v
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
    timeout-minutes: 30
'on':
  push:
    paths:
    - fractopo/**.py
    - tests/**.py
    - .github/workflows/conda.yaml
    - pyproject.toml
    - environment.yaml
  workflow_dispatch: {}
